/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author luandrr
 */
public class CalculadoraUI extends javax.swing.JFrame {
    
    private float primeiroNumero = 0;
    private float segundoNumero = 0;
    private float resultado = 0;

    /**
     * Creates new form CalculadoraUI
     */
    public CalculadoraUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlCalculadora = new javax.swing.JPanel();
        jlblPrimeiroNumero = new javax.swing.JLabel();
        jlblSegundoNumero = new javax.swing.JLabel();
        jlblResultado = new javax.swing.JLabel();
        jtxtPrimeiroNumero = new javax.swing.JTextField();
        jtxtSegundoNumero = new javax.swing.JTextField();
        jtxtResultado = new javax.swing.JTextField();
        jbtnSoma = new javax.swing.JButton();
        jbtnSub = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnDiv = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlCalculadora.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculadora"));

        jlblPrimeiroNumero.setText("Primeiro Número");

        jlblSegundoNumero.setText("Segundo Número");

        jlblResultado.setText("Resultado");

        jbtnSoma.setText("Soma");
        jbtnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSomaActionPerformed(evt);
            }
        });

        jbtnSub.setText("Subtração");
        jbtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubActionPerformed(evt);
            }
        });

        jbtnMulti.setText("Multiplicação");
        jbtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiActionPerformed(evt);
            }
        });

        jbtnDiv.setText("Divisão");
        jbtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivActionPerformed(evt);
            }
        });

        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });

        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlCalculadoraLayout = new javax.swing.GroupLayout(jpnlCalculadora);
        jpnlCalculadora.setLayout(jpnlCalculadoraLayout);
        jpnlCalculadoraLayout.setHorizontalGroup(
            jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCalculadoraLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnlCalculadoraLayout.createSequentialGroup()
                            .addComponent(jbtnSub)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnDiv))
                        .addGroup(jpnlCalculadoraLayout.createSequentialGroup()
                            .addComponent(jbtnSoma)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnMulti)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlCalculadoraLayout.createSequentialGroup()
                        .addComponent(jbtnLimpar)
                        .addGap(86, 86, 86)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnlCalculadoraLayout.createSequentialGroup()
                .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlCalculadoraLayout.createSequentialGroup()
                        .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlCalculadoraLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlblPrimeiroNumero))
                            .addGroup(jpnlCalculadoraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlblSegundoNumero))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlCalculadoraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlblResultado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPrimeiroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlCalculadoraLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jpnlCalculadoraLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnDiv, jbtnMulti, jbtnSoma, jbtnSub});

        jpnlCalculadoraLayout.setVerticalGroup(
            jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCalculadoraLayout.createSequentialGroup()
                .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPrimeiroNumero)
                    .addComponent(jtxtPrimeiroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSegundoNumero)
                    .addComponent(jtxtSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblResultado))
                .addGap(18, 18, 18)
                .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSoma)
                    .addComponent(jbtnMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSub)
                    .addComponent(jbtnDiv))
                .addGap(18, 18, 18)
                .addComponent(jbtnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jbtnSair)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        jtxtPrimeiroNumero.setText("");
        jtxtSegundoNumero.setText("");
        jtxtResultado.setText("");
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jbtnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSomaActionPerformed
        primeiroNumero = Float.parseFloat(jtxtPrimeiroNumero.getText());
        segundoNumero = Float.parseFloat(jtxtSegundoNumero.getText());
        resultado = primeiroNumero+segundoNumero;
        jtxtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jbtnSomaActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        primeiroNumero = Float.parseFloat(jtxtPrimeiroNumero.getText());
        segundoNumero = Float.parseFloat(jtxtSegundoNumero.getText());
        resultado = primeiroNumero*segundoNumero;
        jtxtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubActionPerformed
        primeiroNumero = Float.parseFloat(jtxtPrimeiroNumero.getText());
        segundoNumero = Float.parseFloat(jtxtSegundoNumero.getText());
        resultado = primeiroNumero-segundoNumero;
        jtxtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jbtnSubActionPerformed

    private void jbtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivActionPerformed
        primeiroNumero = Float.parseFloat(jtxtPrimeiroNumero.getText());
        segundoNumero = Float.parseFloat(jtxtSegundoNumero.getText());
        resultado = primeiroNumero/segundoNumero;
        jtxtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jbtnDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnDiv;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JButton jbtnSoma;
    private javax.swing.JButton jbtnSub;
    private javax.swing.JLabel jlblPrimeiroNumero;
    private javax.swing.JLabel jlblResultado;
    private javax.swing.JLabel jlblSegundoNumero;
    private javax.swing.JPanel jpnlCalculadora;
    private javax.swing.JTextField jtxtPrimeiroNumero;
    private javax.swing.JTextField jtxtResultado;
    private javax.swing.JTextField jtxtSegundoNumero;
    // End of variables declaration//GEN-END:variables
}
